name: Manual

on:
  workflow_dispatch:
    inputs:
      ocaml-compiler-version:
        description: The OCaml compiler version with which to run the tests
        type: string
        required: false
        default: '5.2.1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/_build_and_test.yaml
    with:
      ocaml-compiler-version: ${{ inputs.ocaml-compiler-version }}
