name: Run Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/_build_and_test.yaml

  linting:
    name: Check Formatting
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Set-up OCaml and Opam
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.2.1'
          dune-cache: true

      - name: Opam install
        run: |
          opam install . --deps-only --with-test -y
          eval $(opam env)
          make main

      - name: Check formatting
        uses: ocaml/setup-ocaml/lint-fmt@v3
